spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    url: jdbc:h2:mem:dev
    username: sa
    password: password
    driver-class-name: org.h2.Driver


logging:
  level:
    root: INFO
    org.springframework: INFO
